services:
   algorithms4pepprotgraphs-env:
    build: .
    command: nvidia-smi
    container_name: algorithms4pepprotgraphs-env
    volumes:
      - .:/opt/project
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
   jupyter:
    build:
      context: .
      dockerfile: Dockerfile-jupyter

    tmpfs:
      - /home/jovyan/work/algorithms4pepprotgraphs

    volumes:
      - ./dataset:/home/jovyan/work/algorithms4pepprotgraphs/dataset:ro
      - ./db:/home/jovyan/work/algorithms4pepprotgraphs/db:ro
      - ./module:/home/jovyan/work/algorithms4pepprotgraphs/module/:ro
      - ./output:/home/jovyan/work/algorithms4pepprotgraphs/output:ro
      - ./setting:/home/jovyan/work/algorithms4pepprotgraphs/setting:ro
      - ./util:/home/jovyan/work/algorithms4pepprotgraphs/util:ro
      - ./.env.jupyter:/home/jovyan/work/algorithms4pepprotgraphs/.env.jupyter
      - ./notebook:/home/jovyan/work/

    ports:
      - 8888:8888
    container_name: jupyter
    command: "start-notebook.sh --NotebookApp.token='' --NotebookApp.base_url=/jupyter"
    depends_on:
      - algorithms4pepprotgraphs-env
