services:
   algorithms4pepprotgraphs-env:
    build: .
    command: nvidia-smi
    container_name: algorithms4pepprotgraphs-env
    volumes:
      - .:/opt/project
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
   jupyter:
    build:
      context: .
      dockerfile: Dockerfile-jupyter
    tmpfs:
      - /home/jovyan/work/notebooks/utils
    volumes:
      - ./datasets:/home/jovyan/work/datasets
      - ./data_parquet_starpep:/home/jovyan/work/data_parquet_starpep
      - ./notebooks:/home/jovyan/work/notebooks
      - ./output:/home/jovyan/work/output
      - ./utils/pdb_parser.py:/home/jovyan/work/notebooks/utils/pdb_parser.py:ro
      - ./utils/distances_database_manager.py:/home/jovyan/work/notebooks/utils/distances_database_manager.py:ro
      - ./utils/plotting.py:/home/jovyan/work/notebooks/utils/plotting.py:ro
      - ./utils/vector_operations.py:/home/jovyan/work/notebooks/utils/vector_operations.py:ro
    ports:
      - 8888:8888
    container_name: jupyter
    command: "start-notebook.sh --NotebookApp.token='' --NotebookApp.base_url=/jupyter"
    depends_on:
      - algorithms4pepprotgraphs-env

volumes:
  datasets:
  data:
  notebooks:
  output:
  utils:
