version: '3'
services:
  jupyter:
    build: .
    volumes:
      - ./database:/home/jovyan/work/database
      - ./notebooks:/home/jovyan/work/notebooks
      - ./output:/home/jovyan/work/output
      - ./utils:/home/jovyan/work/utils
    ports:
      - 8888:8888
    container_name: algorithms4PepProtGraphs
    command: "start-notebook.sh --NotebookApp.token='' --NotebookApp.base_url=/Algorithms4PepProtGraphs"
